# Use PHP 8.3 FPM on Alpine
FROM php:8.3.13-fpm-alpine

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apk add --no-cache git curl nano \
    libpng libpng-dev libpq-dev libjpeg-turbo-dev libwebp-dev \
    zlib-dev gd-dev zip libzip-dev supervisor \
    && docker-php-ext-install exif pcntl pdo_pgsql pgsql fileinfo zip bcmath calendar gd opcache

# Copy Composer from the official Composer image
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

# Set permissions for Laravel writable directories
RUN addgroup -g 1000 laravel && adduser -G laravel -u 1000 -D laravel

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Run Supervisor
CMD ["/usr/bin/supervisord", "-c", "/var/www/html/docker/supervisor/supervisord.conf"]